# Updated unified Docker with LangChain support
services:
  # PostgreSQL with pgvector + LangChain
  postgres:
    image: pgvector/pgvector:pg16
    container_name: deeds-postgres
    environment:
      POSTGRES_DB: prosecutor_db
      POSTGRES_USER: legal_admin
      POSTGRES_PASSWORD: LegalSecure2024!
      DATABASE_URL: postgresql://legal_admin:LegalSecure2024!@localhost:5432/prosecutor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    command: >
      postgres 
      -c shared_preload_libraries=vector 
      -c max_connections=200
    networks:
      - deeds-network

  # Redis for LangChain caching
  redis:
    image: redis:7-alpine
    container_name: deeds-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb
    volumes:
      - redis_data:/data
    networks:
      - deeds-network

  # Qdrant for vector storage
  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: deeds-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - deeds-network

  # RabbitMQ for async processing
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: deeds-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - deeds-network

  # GPU Ollama for LangChain
  ollama:
    image: ollama/ollama:latest
    container_name: deeds-ollama-gpu
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - deeds-network

  # LangChain API service
  langchain-api:
    build:
      context: ./sveltekit-frontend
      dockerfile: Dockerfile.langchain
    container_name: deeds-langchain
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://legal_admin:LegalSecure2024!@deeds-postgres:5432/prosecutor_db
      - OLLAMA_URL=http://deeds-ollama-gpu:11434
      - REDIS_URL=redis://deeds-redis:6379
    depends_on:
      - postgres
      - ollama
      - redis
    networks:
      - deeds-network

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
  ollama_data:

networks:
  deeds-network:
    driver: bridge
