
services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: deeds-ollama-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./models:/models
    environment:
      - OLLAMA_MODELS=/models
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_FLASH_ATTENTION=1 # Enabled for RTX/Ampere GPUs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ai-app-network

  sveltekit:
    build:
      context: ./sveltekit-frontend
      dockerfile: Dockerfile
    container_name: sveltekit-app
    ports:
      - "5173:5173"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - PUBLIC_ORIGIN=http://localhost:5173
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ai-app-network

  neo4j:
    image: neo4j:5.15-community
    container_name: deeds-neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/LegalSecure2024!
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "cypher-shell",
          "-u",
          "neo4j",
          "-p",
          "LegalSecure2024!",
          "RETURN 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ai-app-network

volumes:
  ollama_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  ai-app-network:
    driver: bridge
