# Qdrant Local Configuration for Windows
# Simplified configuration for local development

service:
  host: 127.0.0.1
  http_port: 6333
  grpc_port: 6334
  enable_cors: true
  max_request_size_mb: 64
  max_workers: 4

storage:
  # Local storage path for Windows
  storage_path: ./qdrant_storage
  
  optimizers:
    memmap_threshold_kb: 524288
    indexing_threshold_kb: 10000
    flush_interval_sec: 30
    max_optimization_threads: 2
  
  performance:
    max_search_threads: 4
    search_timeout_ms: 30000
    max_write_batch_size: 500
    write_timeout_ms: 10000

# Logging
log_level: "INFO"

# Disable telemetry for privacy
telemetry_disabled: true

# No cluster for local development
cluster:
  enabled: false