// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: proto/gpu_service.proto

package gpu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GPUProcessingService_ProcessStream_FullMethodName      = "/gpu_rag_system.GPUProcessingService/ProcessStream"
	GPUProcessingService_ProcessSemantic_FullMethodName    = "/gpu_rag_system.GPUProcessingService/ProcessSemantic"
	GPUProcessingService_QueryRAG_FullMethodName           = "/gpu_rag_system.GPUProcessingService/QueryRAG"
	GPUProcessingService_StreamRAG_FullMethodName          = "/gpu_rag_system.GPUProcessingService/StreamRAG"
	GPUProcessingService_GetRecommendations_FullMethodName = "/gpu_rag_system.GPUProcessingService/GetRecommendations"
	GPUProcessingService_HealthCheck_FullMethodName        = "/gpu_rag_system.GPUProcessingService/HealthCheck"
	GPUProcessingService_GetMetrics_FullMethodName         = "/gpu_rag_system.GPUProcessingService/GetMetrics"
)

// GPUProcessingServiceClient is the client API for GPUProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GPUProcessingServiceClient interface {
	// Bidirectional streaming for real-time processing
	ProcessStream(ctx context.Context, opts ...grpc.CallOption) (GPUProcessingService_ProcessStreamClient, error)
	// Semantic operations
	ProcessSemantic(ctx context.Context, in *SemanticRequest, opts ...grpc.CallOption) (*ProcessingResult, error)
	// Enhanced RAG pipeline
	QueryRAG(ctx context.Context, in *RAGRequest, opts ...grpc.CallOption) (*RAGResponse, error)
	StreamRAG(ctx context.Context, in *RAGRequest, opts ...grpc.CallOption) (GPUProcessingService_StreamRAGClient, error)
	// Recommendation system
	GetRecommendations(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error)
	// System health and metrics
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type gPUProcessingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGPUProcessingServiceClient(cc grpc.ClientConnInterface) GPUProcessingServiceClient {
	return &gPUProcessingServiceClient{cc}
}

func (c *gPUProcessingServiceClient) ProcessStream(ctx context.Context, opts ...grpc.CallOption) (GPUProcessingService_ProcessStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GPUProcessingService_ServiceDesc.Streams[0], GPUProcessingService_ProcessStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gPUProcessingServiceProcessStreamClient{stream}
	return x, nil
}

type GPUProcessingService_ProcessStreamClient interface {
	Send(*DataChunk) error
	Recv() (*ProcessingResult, error)
	grpc.ClientStream
}

type gPUProcessingServiceProcessStreamClient struct {
	grpc.ClientStream
}

func (x *gPUProcessingServiceProcessStreamClient) Send(m *DataChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gPUProcessingServiceProcessStreamClient) Recv() (*ProcessingResult, error) {
	m := new(ProcessingResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gPUProcessingServiceClient) ProcessSemantic(ctx context.Context, in *SemanticRequest, opts ...grpc.CallOption) (*ProcessingResult, error) {
	out := new(ProcessingResult)
	err := c.cc.Invoke(ctx, GPUProcessingService_ProcessSemantic_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProcessingServiceClient) QueryRAG(ctx context.Context, in *RAGRequest, opts ...grpc.CallOption) (*RAGResponse, error) {
	out := new(RAGResponse)
	err := c.cc.Invoke(ctx, GPUProcessingService_QueryRAG_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProcessingServiceClient) StreamRAG(ctx context.Context, in *RAGRequest, opts ...grpc.CallOption) (GPUProcessingService_StreamRAGClient, error) {
	stream, err := c.cc.NewStream(ctx, &GPUProcessingService_ServiceDesc.Streams[1], GPUProcessingService_StreamRAG_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gPUProcessingServiceStreamRAGClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GPUProcessingService_StreamRAGClient interface {
	Recv() (*RAGResponse, error)
	grpc.ClientStream
}

type gPUProcessingServiceStreamRAGClient struct {
	grpc.ClientStream
}

func (x *gPUProcessingServiceStreamRAGClient) Recv() (*RAGResponse, error) {
	m := new(RAGResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gPUProcessingServiceClient) GetRecommendations(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error) {
	out := new(RecommendationResponse)
	err := c.cc.Invoke(ctx, GPUProcessingService_GetRecommendations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProcessingServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, GPUProcessingService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProcessingServiceClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, GPUProcessingService_GetMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GPUProcessingServiceServer is the server API for GPUProcessingService service.
// All implementations must embed UnimplementedGPUProcessingServiceServer
// for forward compatibility
type GPUProcessingServiceServer interface {
	// Bidirectional streaming for real-time processing
	ProcessStream(GPUProcessingService_ProcessStreamServer) error
	// Semantic operations
	ProcessSemantic(context.Context, *SemanticRequest) (*ProcessingResult, error)
	// Enhanced RAG pipeline
	QueryRAG(context.Context, *RAGRequest) (*RAGResponse, error)
	StreamRAG(*RAGRequest, GPUProcessingService_StreamRAGServer) error
	// Recommendation system
	GetRecommendations(context.Context, *RecommendationRequest) (*RecommendationResponse, error)
	// System health and metrics
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	mustEmbedUnimplementedGPUProcessingServiceServer()
}

// UnimplementedGPUProcessingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGPUProcessingServiceServer struct {
}

func (UnimplementedGPUProcessingServiceServer) ProcessStream(GPUProcessingService_ProcessStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessStream not implemented")
}
func (UnimplementedGPUProcessingServiceServer) ProcessSemantic(context.Context, *SemanticRequest) (*ProcessingResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSemantic not implemented")
}
func (UnimplementedGPUProcessingServiceServer) QueryRAG(context.Context, *RAGRequest) (*RAGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRAG not implemented")
}
func (UnimplementedGPUProcessingServiceServer) StreamRAG(*RAGRequest, GPUProcessingService_StreamRAGServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamRAG not implemented")
}
func (UnimplementedGPUProcessingServiceServer) GetRecommendations(context.Context, *RecommendationRequest) (*RecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedGPUProcessingServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGPUProcessingServiceServer) GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedGPUProcessingServiceServer) mustEmbedUnimplementedGPUProcessingServiceServer() {}

// UnsafeGPUProcessingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GPUProcessingServiceServer will
// result in compilation errors.
type UnsafeGPUProcessingServiceServer interface {
	mustEmbedUnimplementedGPUProcessingServiceServer()
}

func RegisterGPUProcessingServiceServer(s grpc.ServiceRegistrar, srv GPUProcessingServiceServer) {
	s.RegisterService(&GPUProcessingService_ServiceDesc, srv)
}

func _GPUProcessingService_ProcessStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GPUProcessingServiceServer).ProcessStream(&gPUProcessingServiceProcessStreamServer{stream})
}

type GPUProcessingService_ProcessStreamServer interface {
	Send(*ProcessingResult) error
	Recv() (*DataChunk, error)
	grpc.ServerStream
}

type gPUProcessingServiceProcessStreamServer struct {
	grpc.ServerStream
}

func (x *gPUProcessingServiceProcessStreamServer) Send(m *ProcessingResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gPUProcessingServiceProcessStreamServer) Recv() (*DataChunk, error) {
	m := new(DataChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GPUProcessingService_ProcessSemantic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemanticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProcessingServiceServer).ProcessSemantic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProcessingService_ProcessSemantic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProcessingServiceServer).ProcessSemantic(ctx, req.(*SemanticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProcessingService_QueryRAG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProcessingServiceServer).QueryRAG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProcessingService_QueryRAG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProcessingServiceServer).QueryRAG(ctx, req.(*RAGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProcessingService_StreamRAG_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RAGRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GPUProcessingServiceServer).StreamRAG(m, &gPUProcessingServiceStreamRAGServer{stream})
}

type GPUProcessingService_StreamRAGServer interface {
	Send(*RAGResponse) error
	grpc.ServerStream
}

type gPUProcessingServiceStreamRAGServer struct {
	grpc.ServerStream
}

func (x *gPUProcessingServiceStreamRAGServer) Send(m *RAGResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GPUProcessingService_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProcessingServiceServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProcessingService_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProcessingServiceServer).GetRecommendations(ctx, req.(*RecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProcessingService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProcessingServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProcessingService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProcessingServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProcessingService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProcessingServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProcessingService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProcessingServiceServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GPUProcessingService_ServiceDesc is the grpc.ServiceDesc for GPUProcessingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GPUProcessingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gpu_rag_system.GPUProcessingService",
	HandlerType: (*GPUProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSemantic",
			Handler:    _GPUProcessingService_ProcessSemantic_Handler,
		},
		{
			MethodName: "QueryRAG",
			Handler:    _GPUProcessingService_QueryRAG_Handler,
		},
		{
			MethodName: "GetRecommendations",
			Handler:    _GPUProcessingService_GetRecommendations_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GPUProcessingService_HealthCheck_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _GPUProcessingService_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessStream",
			Handler:       _GPUProcessingService_ProcessStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamRAG",
			Handler:       _GPUProcessingService_StreamRAG_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/gpu_service.proto",
}
