// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: api/citations/v1/citations.proto

package citationsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CitationService_IngestBatch_FullMethodName   = "/api.citations.v1.CitationService/IngestBatch"
	CitationService_ListCitations_FullMethodName = "/api.citations.v1.CitationService/ListCitations"
)

// CitationServiceClient is the client API for CitationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CitationServiceClient interface {
	IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchResponse, error)
	ListCitations(ctx context.Context, in *ListCitationsRequest, opts ...grpc.CallOption) (*ListCitationsResponse, error)
}

type citationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCitationServiceClient(cc grpc.ClientConnInterface) CitationServiceClient {
	return &citationServiceClient{cc}
}

func (c *citationServiceClient) IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestBatchResponse)
	err := c.cc.Invoke(ctx, CitationService_IngestBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *citationServiceClient) ListCitations(ctx context.Context, in *ListCitationsRequest, opts ...grpc.CallOption) (*ListCitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCitationsResponse)
	err := c.cc.Invoke(ctx, CitationService_ListCitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CitationServiceServer is the server API for CitationService service.
// All implementations must embed UnimplementedCitationServiceServer
// for forward compatibility
type CitationServiceServer interface {
	IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchResponse, error)
	ListCitations(context.Context, *ListCitationsRequest) (*ListCitationsResponse, error)
	mustEmbedUnimplementedCitationServiceServer()
}

// UnimplementedCitationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCitationServiceServer struct {
}

func (UnimplementedCitationServiceServer) IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestBatch not implemented")
}
func (UnimplementedCitationServiceServer) ListCitations(context.Context, *ListCitationsRequest) (*ListCitationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCitations not implemented")
}
func (UnimplementedCitationServiceServer) mustEmbedUnimplementedCitationServiceServer() {}

// UnsafeCitationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CitationServiceServer will
// result in compilation errors.
type UnsafeCitationServiceServer interface {
	mustEmbedUnimplementedCitationServiceServer()
}

func RegisterCitationServiceServer(s grpc.ServiceRegistrar, srv CitationServiceServer) {
	s.RegisterService(&CitationService_ServiceDesc, srv)
}

func _CitationService_IngestBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CitationServiceServer).IngestBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CitationService_IngestBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CitationServiceServer).IngestBatch(ctx, req.(*IngestBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CitationService_ListCitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CitationServiceServer).ListCitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CitationService_ListCitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CitationServiceServer).ListCitations(ctx, req.(*ListCitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CitationService_ServiceDesc is the grpc.ServiceDesc for CitationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CitationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.citations.v1.CitationService",
	HandlerType: (*CitationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestBatch",
			Handler:    _CitationService_IngestBatch_Handler,
		},
		{
			MethodName: "ListCitations",
			Handler:    _CitationService_ListCitations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/citations/v1/citations.proto",
}
