# Docker Compose Override for Memory Limits and WSL2 Optimization
# Place this file as docker-compose.override.yml for automatic loading

services:
  postgres:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
    environment:
      # PostgreSQL memory optimization
      POSTGRES_SHARED_BUFFERS: 128MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 256MB
      POSTGRES_WORK_MEM: 4MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB

  qdrant:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
    environment:
      # Qdrant memory optimization
      QDRANT__STORAGE__PERFORMANCE__MAX_SEARCH_THREADS: 2

  redis:
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
        reservations:
          memory: 128M
          cpus: "0.1"
    command: redis-server --appendonly yes --maxmemory 200mb --maxmemory-policy allkeys-lru --tcp-keepalive 60

  # Uncomment if using Ollama
  # ollama:
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 2G
  #         cpus: '1.0'
  #       reservations:
  #         memory: 1G
  #         cpus: '0.5'
