// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.4
// source: feedback.proto

package feedback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedbackEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // inference job id
	TsUnixMs      int64                  `protobuf:"varint,4,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`                                                                       // "accept"|"reject"|"flag"
	Reward        float32                `protobuf:"fixed32,6,opt,name=reward,proto3" json:"reward,omitempty"`                                                                     // optional numeric reward
	Vector        []float32              `protobuf:"fixed32,7,rep,packed,name=vector,proto3" json:"vector,omitempty"`                                                              // flattened tensor (float32)
	Meta          map[string]string      `protobuf:"bytes,8,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., {"path":"file1.md","route":"search"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackEvent) Reset() {
	*x = FeedbackEvent{}
	mi := &file_feedback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackEvent) ProtoMessage() {}

func (x *FeedbackEvent) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackEvent.ProtoReflect.Descriptor instead.
func (*FeedbackEvent) Descriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{0}
}

func (x *FeedbackEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedbackEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FeedbackEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FeedbackEvent) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *FeedbackEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FeedbackEvent) GetReward() float32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *FeedbackEvent) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *FeedbackEvent) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type FeedbackBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*FeedbackEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackBatch) Reset() {
	*x = FeedbackBatch{}
	mi := &file_feedback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackBatch) ProtoMessage() {}

func (x *FeedbackBatch) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackBatch.ProtoReflect.Descriptor instead.
func (*FeedbackBatch) Descriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{1}
}

func (x *FeedbackBatch) GetEvents() []*FeedbackEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_feedback_proto protoreflect.FileDescriptor

const file_feedback_proto_rawDesc = "" +
	"\n" +
	"\x0efeedback.proto\x12\x0eyorha.feedback\"\xab\x02\n" +
	"\rFeedbackEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x04 \x01(\x03R\btsUnixMs\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x16\n" +
	"\x06reward\x18\x06 \x01(\x02R\x06reward\x12\x16\n" +
	"\x06vector\x18\a \x03(\x02R\x06vector\x12;\n" +
	"\x04meta\x18\b \x03(\v2'.yorha.feedback.FeedbackEvent.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\rFeedbackBatch\x125\n" +
	"\x06events\x18\x01 \x03(\v2\x1d.yorha.feedback.FeedbackEventR\x06eventsB=Z;legal-ai-production/go-microservice/proto/feedback;feedbackb\x06proto3"

var (
	file_feedback_proto_rawDescOnce sync.Once
	file_feedback_proto_rawDescData []byte
)

func file_feedback_proto_rawDescGZIP() []byte {
	file_feedback_proto_rawDescOnce.Do(func() {
		file_feedback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedback_proto_rawDesc), len(file_feedback_proto_rawDesc)))
	})
	return file_feedback_proto_rawDescData
}

var file_feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_feedback_proto_goTypes = []any{
	(*FeedbackEvent)(nil), // 0: yorha.feedback.FeedbackEvent
	(*FeedbackBatch)(nil), // 1: yorha.feedback.FeedbackBatch
	nil,                   // 2: yorha.feedback.FeedbackEvent.MetaEntry
}
var file_feedback_proto_depIdxs = []int32{
	2, // 0: yorha.feedback.FeedbackEvent.meta:type_name -> yorha.feedback.FeedbackEvent.MetaEntry
	0, // 1: yorha.feedback.FeedbackBatch.events:type_name -> yorha.feedback.FeedbackEvent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_feedback_proto_init() }
func file_feedback_proto_init() {
	if File_feedback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedback_proto_rawDesc), len(file_feedback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feedback_proto_goTypes,
		DependencyIndexes: file_feedback_proto_depIdxs,
		MessageInfos:      file_feedback_proto_msgTypes,
	}.Build()
	File_feedback_proto = out.File
	file_feedback_proto_goTypes = nil
	file_feedback_proto_depIdxs = nil
}
