version: "3.8"
services:
  redis-vector:
    image: redis/redis-stack:latest
    container_name: redis-vector-db
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight web UI
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-vector-db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  redis_data:
  qdrant_data:
