// aiserver.proto - Enterprise-grade Vector Processing Service
// Version 2.0 - High-Performance gRPC/Protobuf Communication

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: aiserver.proto

package aiserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VectorService_ProcessRotation_FullMethodName        = "/aiserver.VectorService/ProcessRotation"
	VectorService_ProcessSimilarity_FullMethodName      = "/aiserver.VectorService/ProcessSimilarity"
	VectorService_ProcessLegalDocument_FullMethodName   = "/aiserver.VectorService/ProcessLegalDocument"
	VectorService_FindSimilarDocuments_FullMethodName   = "/aiserver.VectorService/FindSimilarDocuments"
	VectorService_BatchProcessVectors_FullMethodName    = "/aiserver.VectorService/BatchProcessVectors"
	VectorService_BatchComputeSimilarity_FullMethodName = "/aiserver.VectorService/BatchComputeSimilarity"
	VectorService_StreamVectorProcessing_FullMethodName = "/aiserver.VectorService/StreamVectorProcessing"
	VectorService_HealthCheck_FullMethodName            = "/aiserver.VectorService/HealthCheck"
	VectorService_GetMetrics_FullMethodName             = "/aiserver.VectorService/GetMetrics"
)

// VectorServiceClient is the client API for VectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The core vector processing service definition
type VectorServiceClient interface {
	// Basic vector operations
	ProcessRotation(ctx context.Context, in *VectorRequest, opts ...grpc.CallOption) (*VectorResponse, error)
	ProcessSimilarity(ctx context.Context, in *SimilarityRequest, opts ...grpc.CallOption) (*SimilarityResponse, error)
	// Advanced legal document processing
	ProcessLegalDocument(ctx context.Context, in *LegalDocumentRequest, opts ...grpc.CallOption) (*LegalDocumentResponse, error)
	FindSimilarDocuments(ctx context.Context, in *DocumentSimilarityRequest, opts ...grpc.CallOption) (*DocumentSimilarityResponse, error)
	// Batch operations for high throughput
	BatchProcessVectors(ctx context.Context, in *BatchVectorRequest, opts ...grpc.CallOption) (*BatchVectorResponse, error)
	BatchComputeSimilarity(ctx context.Context, in *BatchSimilarityRequest, opts ...grpc.CallOption) (*BatchSimilarityResponse, error)
	// Real-time streaming operations
	StreamVectorProcessing(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamVectorRequest, StreamVectorResponse], error)
	// Health and monitoring
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type vectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorServiceClient(cc grpc.ClientConnInterface) VectorServiceClient {
	return &vectorServiceClient{cc}
}

func (c *vectorServiceClient) ProcessRotation(ctx context.Context, in *VectorRequest, opts ...grpc.CallOption) (*VectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorResponse)
	err := c.cc.Invoke(ctx, VectorService_ProcessRotation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) ProcessSimilarity(ctx context.Context, in *SimilarityRequest, opts ...grpc.CallOption) (*SimilarityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimilarityResponse)
	err := c.cc.Invoke(ctx, VectorService_ProcessSimilarity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) ProcessLegalDocument(ctx context.Context, in *LegalDocumentRequest, opts ...grpc.CallOption) (*LegalDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LegalDocumentResponse)
	err := c.cc.Invoke(ctx, VectorService_ProcessLegalDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) FindSimilarDocuments(ctx context.Context, in *DocumentSimilarityRequest, opts ...grpc.CallOption) (*DocumentSimilarityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentSimilarityResponse)
	err := c.cc.Invoke(ctx, VectorService_FindSimilarDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) BatchProcessVectors(ctx context.Context, in *BatchVectorRequest, opts ...grpc.CallOption) (*BatchVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_BatchProcessVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) BatchComputeSimilarity(ctx context.Context, in *BatchSimilarityRequest, opts ...grpc.CallOption) (*BatchSimilarityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSimilarityResponse)
	err := c.cc.Invoke(ctx, VectorService_BatchComputeSimilarity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) StreamVectorProcessing(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamVectorRequest, StreamVectorResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VectorService_ServiceDesc.Streams[0], VectorService_StreamVectorProcessing_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamVectorRequest, StreamVectorResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VectorService_StreamVectorProcessingClient = grpc.BidiStreamingClient[StreamVectorRequest, StreamVectorResponse]

func (c *vectorServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, VectorService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, VectorService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorServiceServer is the server API for VectorService service.
// All implementations must embed UnimplementedVectorServiceServer
// for forward compatibility.
//
// The core vector processing service definition
type VectorServiceServer interface {
	// Basic vector operations
	ProcessRotation(context.Context, *VectorRequest) (*VectorResponse, error)
	ProcessSimilarity(context.Context, *SimilarityRequest) (*SimilarityResponse, error)
	// Advanced legal document processing
	ProcessLegalDocument(context.Context, *LegalDocumentRequest) (*LegalDocumentResponse, error)
	FindSimilarDocuments(context.Context, *DocumentSimilarityRequest) (*DocumentSimilarityResponse, error)
	// Batch operations for high throughput
	BatchProcessVectors(context.Context, *BatchVectorRequest) (*BatchVectorResponse, error)
	BatchComputeSimilarity(context.Context, *BatchSimilarityRequest) (*BatchSimilarityResponse, error)
	// Real-time streaming operations
	StreamVectorProcessing(grpc.BidiStreamingServer[StreamVectorRequest, StreamVectorResponse]) error
	// Health and monitoring
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	mustEmbedUnimplementedVectorServiceServer()
}

// UnimplementedVectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVectorServiceServer struct{}

func (UnimplementedVectorServiceServer) ProcessRotation(context.Context, *VectorRequest) (*VectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessRotation not implemented")
}
func (UnimplementedVectorServiceServer) ProcessSimilarity(context.Context, *SimilarityRequest) (*SimilarityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSimilarity not implemented")
}
func (UnimplementedVectorServiceServer) ProcessLegalDocument(context.Context, *LegalDocumentRequest) (*LegalDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessLegalDocument not implemented")
}
func (UnimplementedVectorServiceServer) FindSimilarDocuments(context.Context, *DocumentSimilarityRequest) (*DocumentSimilarityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSimilarDocuments not implemented")
}
func (UnimplementedVectorServiceServer) BatchProcessVectors(context.Context, *BatchVectorRequest) (*BatchVectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchProcessVectors not implemented")
}
func (UnimplementedVectorServiceServer) BatchComputeSimilarity(context.Context, *BatchSimilarityRequest) (*BatchSimilarityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchComputeSimilarity not implemented")
}
func (UnimplementedVectorServiceServer) StreamVectorProcessing(grpc.BidiStreamingServer[StreamVectorRequest, StreamVectorResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamVectorProcessing not implemented")
}
func (UnimplementedVectorServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedVectorServiceServer) GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedVectorServiceServer) mustEmbedUnimplementedVectorServiceServer() {}
func (UnimplementedVectorServiceServer) testEmbeddedByValue()                       {}

// UnsafeVectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorServiceServer will
// result in compilation errors.
type UnsafeVectorServiceServer interface {
	mustEmbedUnimplementedVectorServiceServer()
}

func RegisterVectorServiceServer(s grpc.ServiceRegistrar, srv VectorServiceServer) {
	// If the following call pancis, it indicates UnimplementedVectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VectorService_ServiceDesc, srv)
}

func _VectorService_ProcessRotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).ProcessRotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_ProcessRotation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).ProcessRotation(ctx, req.(*VectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_ProcessSimilarity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilarityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).ProcessSimilarity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_ProcessSimilarity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).ProcessSimilarity(ctx, req.(*SimilarityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_ProcessLegalDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LegalDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).ProcessLegalDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_ProcessLegalDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).ProcessLegalDocument(ctx, req.(*LegalDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_FindSimilarDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentSimilarityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).FindSimilarDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_FindSimilarDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).FindSimilarDocuments(ctx, req.(*DocumentSimilarityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_BatchProcessVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).BatchProcessVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_BatchProcessVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).BatchProcessVectors(ctx, req.(*BatchVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_BatchComputeSimilarity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSimilarityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).BatchComputeSimilarity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_BatchComputeSimilarity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).BatchComputeSimilarity(ctx, req.(*BatchSimilarityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_StreamVectorProcessing_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VectorServiceServer).StreamVectorProcessing(&grpc.GenericServerStream[StreamVectorRequest, StreamVectorResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VectorService_StreamVectorProcessingServer = grpc.BidiStreamingServer[StreamVectorRequest, StreamVectorResponse]

func _VectorService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VectorService_ServiceDesc is the grpc.ServiceDesc for VectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiserver.VectorService",
	HandlerType: (*VectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessRotation",
			Handler:    _VectorService_ProcessRotation_Handler,
		},
		{
			MethodName: "ProcessSimilarity",
			Handler:    _VectorService_ProcessSimilarity_Handler,
		},
		{
			MethodName: "ProcessLegalDocument",
			Handler:    _VectorService_ProcessLegalDocument_Handler,
		},
		{
			MethodName: "FindSimilarDocuments",
			Handler:    _VectorService_FindSimilarDocuments_Handler,
		},
		{
			MethodName: "BatchProcessVectors",
			Handler:    _VectorService_BatchProcessVectors_Handler,
		},
		{
			MethodName: "BatchComputeSimilarity",
			Handler:    _VectorService_BatchComputeSimilarity_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _VectorService_HealthCheck_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _VectorService_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamVectorProcessing",
			Handler:       _VectorService_StreamVectorProcessing_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "aiserver.proto",
}

const (
	AsyncJobService_SubmitAsyncJob_FullMethodName = "/aiserver.AsyncJobService/SubmitAsyncJob"
	AsyncJobService_GetJobStatus_FullMethodName   = "/aiserver.AsyncJobService/GetJobStatus"
	AsyncJobService_GetJobResult_FullMethodName   = "/aiserver.AsyncJobService/GetJobResult"
	AsyncJobService_CancelJob_FullMethodName      = "/aiserver.AsyncJobService/CancelJob"
)

// AsyncJobServiceClient is the client API for AsyncJobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Enhanced service for RabbitMQ integration
type AsyncJobServiceClient interface {
	SubmitAsyncJob(ctx context.Context, in *AsyncJobRequest, opts ...grpc.CallOption) (*AsyncJobResponse, error)
	GetJobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error)
	GetJobResult(ctx context.Context, in *JobResultRequest, opts ...grpc.CallOption) (*JobResultResponse, error)
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
}

type asyncJobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAsyncJobServiceClient(cc grpc.ClientConnInterface) AsyncJobServiceClient {
	return &asyncJobServiceClient{cc}
}

func (c *asyncJobServiceClient) SubmitAsyncJob(ctx context.Context, in *AsyncJobRequest, opts ...grpc.CallOption) (*AsyncJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AsyncJobResponse)
	err := c.cc.Invoke(ctx, AsyncJobService_SubmitAsyncJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncJobServiceClient) GetJobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatusResponse)
	err := c.cc.Invoke(ctx, AsyncJobService_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncJobServiceClient) GetJobResult(ctx context.Context, in *JobResultRequest, opts ...grpc.CallOption) (*JobResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResultResponse)
	err := c.cc.Invoke(ctx, AsyncJobService_GetJobResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncJobServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, AsyncJobService_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsyncJobServiceServer is the server API for AsyncJobService service.
// All implementations must embed UnimplementedAsyncJobServiceServer
// for forward compatibility.
//
// Enhanced service for RabbitMQ integration
type AsyncJobServiceServer interface {
	SubmitAsyncJob(context.Context, *AsyncJobRequest) (*AsyncJobResponse, error)
	GetJobStatus(context.Context, *JobStatusRequest) (*JobStatusResponse, error)
	GetJobResult(context.Context, *JobResultRequest) (*JobResultResponse, error)
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	mustEmbedUnimplementedAsyncJobServiceServer()
}

// UnimplementedAsyncJobServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAsyncJobServiceServer struct{}

func (UnimplementedAsyncJobServiceServer) SubmitAsyncJob(context.Context, *AsyncJobRequest) (*AsyncJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAsyncJob not implemented")
}
func (UnimplementedAsyncJobServiceServer) GetJobStatus(context.Context, *JobStatusRequest) (*JobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedAsyncJobServiceServer) GetJobResult(context.Context, *JobResultRequest) (*JobResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobResult not implemented")
}
func (UnimplementedAsyncJobServiceServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedAsyncJobServiceServer) mustEmbedUnimplementedAsyncJobServiceServer() {}
func (UnimplementedAsyncJobServiceServer) testEmbeddedByValue()                         {}

// UnsafeAsyncJobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsyncJobServiceServer will
// result in compilation errors.
type UnsafeAsyncJobServiceServer interface {
	mustEmbedUnimplementedAsyncJobServiceServer()
}

func RegisterAsyncJobServiceServer(s grpc.ServiceRegistrar, srv AsyncJobServiceServer) {
	// If the following call pancis, it indicates UnimplementedAsyncJobServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AsyncJobService_ServiceDesc, srv)
}

func _AsyncJobService_SubmitAsyncJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsyncJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncJobServiceServer).SubmitAsyncJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncJobService_SubmitAsyncJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncJobServiceServer).SubmitAsyncJob(ctx, req.(*AsyncJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncJobService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncJobServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncJobService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncJobServiceServer).GetJobStatus(ctx, req.(*JobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncJobService_GetJobResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncJobServiceServer).GetJobResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncJobService_GetJobResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncJobServiceServer).GetJobResult(ctx, req.(*JobResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncJobService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncJobServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncJobService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncJobServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AsyncJobService_ServiceDesc is the grpc.ServiceDesc for AsyncJobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AsyncJobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiserver.AsyncJobService",
	HandlerType: (*AsyncJobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitAsyncJob",
			Handler:    _AsyncJobService_SubmitAsyncJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _AsyncJobService_GetJobStatus_Handler,
		},
		{
			MethodName: "GetJobResult",
			Handler:    _AsyncJobService_GetJobResult_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _AsyncJobService_CancelJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aiserver.proto",
}
