// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: vectorservice/v1/vector_service.proto

package vectorservicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	VectorService_ProcessRotation_FullMethodName   = "/vectorservice.v1.VectorService/ProcessRotation"
	VectorService_ProcessSimilarity_FullMethodName = "/vectorservice.v1.VectorService/ProcessSimilarity"
	VectorService_ProcessEmbedding_FullMethodName  = "/vectorservice.v1.VectorService/ProcessEmbedding"
	VectorService_ProcessBatch_FullMethodName      = "/vectorservice.v1.VectorService/ProcessBatch"
	VectorService_HealthCheck_FullMethodName       = "/vectorservice.v1.VectorService/HealthCheck"
	VectorService_GetMetrics_FullMethodName        = "/vectorservice.v1.VectorService/GetMetrics"
)

// VectorServiceClient is the client API for VectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorServiceClient interface {
	ProcessRotation(ctx context.Context, in *ProcessRotationRequest, opts ...grpc.CallOption) (*ProcessRotationResponse, error)
	ProcessSimilarity(ctx context.Context, in *ProcessSimilarityRequest, opts ...grpc.CallOption) (*ProcessSimilarityResponse, error)
	ProcessEmbedding(ctx context.Context, in *ProcessEmbeddingRequest, opts ...grpc.CallOption) (*ProcessEmbeddingResponse, error)
	ProcessBatch(ctx context.Context, in *ProcessBatchRequest, opts ...grpc.CallOption) (VectorService_ProcessBatchClient, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
}

type vectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorServiceClient(cc grpc.ClientConnInterface) VectorServiceClient {
	return &vectorServiceClient{cc}
}

func (c *vectorServiceClient) ProcessRotation(ctx context.Context, in *ProcessRotationRequest, opts ...grpc.CallOption) (*ProcessRotationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessRotationResponse)
	err := c.cc.Invoke(ctx, VectorService_ProcessRotation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) ProcessSimilarity(ctx context.Context, in *ProcessSimilarityRequest, opts ...grpc.CallOption) (*ProcessSimilarityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessSimilarityResponse)
	err := c.cc.Invoke(ctx, VectorService_ProcessSimilarity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) ProcessEmbedding(ctx context.Context, in *ProcessEmbeddingRequest, opts ...grpc.CallOption) (*ProcessEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessEmbeddingResponse)
	err := c.cc.Invoke(ctx, VectorService_ProcessEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) ProcessBatch(ctx context.Context, in *ProcessBatchRequest, opts ...grpc.CallOption) (VectorService_ProcessBatchClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VectorService_ServiceDesc.Streams[0], VectorService_ProcessBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &vectorServiceProcessBatchClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VectorService_ProcessBatchClient interface {
	Recv() (*ProcessBatchResponse, error)
	grpc.ClientStream
}

type vectorServiceProcessBatchClient struct {
	grpc.ClientStream
}

func (x *vectorServiceProcessBatchClient) Recv() (*ProcessBatchResponse, error) {
	m := new(ProcessBatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vectorServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, VectorService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, VectorService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorServiceServer is the server API for VectorService service.
// All implementations must embed UnimplementedVectorServiceServer
// for forward compatibility
type VectorServiceServer interface {
	ProcessRotation(context.Context, *ProcessRotationRequest) (*ProcessRotationResponse, error)
	ProcessSimilarity(context.Context, *ProcessSimilarityRequest) (*ProcessSimilarityResponse, error)
	ProcessEmbedding(context.Context, *ProcessEmbeddingRequest) (*ProcessEmbeddingResponse, error)
	ProcessBatch(*ProcessBatchRequest, VectorService_ProcessBatchServer) error
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	mustEmbedUnimplementedVectorServiceServer()
}

// UnimplementedVectorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVectorServiceServer struct {
}

func (UnimplementedVectorServiceServer) ProcessRotation(context.Context, *ProcessRotationRequest) (*ProcessRotationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessRotation not implemented")
}
func (UnimplementedVectorServiceServer) ProcessSimilarity(context.Context, *ProcessSimilarityRequest) (*ProcessSimilarityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSimilarity not implemented")
}
func (UnimplementedVectorServiceServer) ProcessEmbedding(context.Context, *ProcessEmbeddingRequest) (*ProcessEmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessEmbedding not implemented")
}
func (UnimplementedVectorServiceServer) ProcessBatch(*ProcessBatchRequest, VectorService_ProcessBatchServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessBatch not implemented")
}
func (UnimplementedVectorServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedVectorServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedVectorServiceServer) mustEmbedUnimplementedVectorServiceServer() {}

// UnsafeVectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorServiceServer will
// result in compilation errors.
type UnsafeVectorServiceServer interface {
	mustEmbedUnimplementedVectorServiceServer()
}

func RegisterVectorServiceServer(s grpc.ServiceRegistrar, srv VectorServiceServer) {
	s.RegisterService(&VectorService_ServiceDesc, srv)
}

func _VectorService_ProcessRotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).ProcessRotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_ProcessRotation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).ProcessRotation(ctx, req.(*ProcessRotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_ProcessSimilarity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessSimilarityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).ProcessSimilarity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_ProcessSimilarity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).ProcessSimilarity(ctx, req.(*ProcessSimilarityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_ProcessEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).ProcessEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_ProcessEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).ProcessEmbedding(ctx, req.(*ProcessEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_ProcessBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessBatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VectorServiceServer).ProcessBatch(m, &vectorServiceProcessBatchServer{ServerStream: stream})
}

type VectorService_ProcessBatchServer interface {
	Send(*ProcessBatchResponse) error
	grpc.ServerStream
}

type vectorServiceProcessBatchServer struct {
	grpc.ServerStream
}

func (x *vectorServiceProcessBatchServer) Send(m *ProcessBatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VectorService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VectorService_ServiceDesc is the grpc.ServiceDesc for VectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vectorservice.v1.VectorService",
	HandlerType: (*VectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessRotation",
			Handler:    _VectorService_ProcessRotation_Handler,
		},
		{
			MethodName: "ProcessSimilarity",
			Handler:    _VectorService_ProcessSimilarity_Handler,
		},
		{
			MethodName: "ProcessEmbedding",
			Handler:    _VectorService_ProcessEmbedding_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _VectorService_HealthCheck_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _VectorService_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessBatch",
			Handler:       _VectorService_ProcessBatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vectorservice/v1/vector_service.proto",
}
