// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.4
// source: proto/events.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lightweight telemetry from client to server
type Telemetry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId    string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsTyping  bool     `protobuf:"varint,3,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	Visible   bool     `protobuf:"varint,4,opt,name=visible,proto3" json:"visible,omitempty"`
	LongTasks uint32   `protobuf:"varint,5,opt,name=long_tasks,json=longTasks,proto3" json:"long_tasks,omitempty"`
	Hints     []string `protobuf:"bytes,6,rep,name=hints,proto3" json:"hints,omitempty"` // UI hints (viewport buckets, routes)
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *Telemetry) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Telemetry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Telemetry) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

func (x *Telemetry) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Telemetry) GetLongTasks() uint32 {
	if x != nil {
		return x.LongTasks
	}
	return 0
}

func (x *Telemetry) GetHints() []string {
	if x != nil {
		return x.Hints
	}
	return nil
}

// Server → client prefetch plan
type PrefetchPlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls      []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	QdrantIds []string `protobuf:"bytes,2,rep,name=qdrant_ids,json=qdrantIds,proto3" json:"qdrant_ids,omitempty"`
}

func (x *PrefetchPlan) Reset() {
	*x = PrefetchPlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrefetchPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefetchPlan) ProtoMessage() {}

func (x *PrefetchPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefetchPlan.ProtoReflect.Descriptor instead.
func (*PrefetchPlan) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *PrefetchPlan) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *PrefetchPlan) GetQdrantIds() []string {
	if x != nil {
		return x.QdrantIds
	}
	return nil
}

// Generic streaming frame over WebSocket/WebTransport
type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Kind:
	//
	//	*Frame_Telemetry
	//	*Frame_Prefetch
	//	*Frame_SummaryDelta
	Kind isFrame_Kind `protobuf_oneof:"kind"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{2}
}

func (m *Frame) GetKind() isFrame_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *Frame) GetTelemetry() *Telemetry {
	if x, ok := x.GetKind().(*Frame_Telemetry); ok {
		return x.Telemetry
	}
	return nil
}

func (x *Frame) GetPrefetch() *PrefetchPlan {
	if x, ok := x.GetKind().(*Frame_Prefetch); ok {
		return x.Prefetch
	}
	return nil
}

func (x *Frame) GetSummaryDelta() []byte {
	if x, ok := x.GetKind().(*Frame_SummaryDelta); ok {
		return x.SummaryDelta
	}
	return nil
}

type isFrame_Kind interface {
	isFrame_Kind()
}

type Frame_Telemetry struct {
	Telemetry *Telemetry `protobuf:"bytes,1,opt,name=telemetry,proto3,oneof"`
}

type Frame_Prefetch struct {
	Prefetch *PrefetchPlan `protobuf:"bytes,2,opt,name=prefetch,proto3,oneof"`
}

type Frame_SummaryDelta struct {
	SummaryDelta []byte `protobuf:"bytes,3,opt,name=summary_delta,json=summaryDelta,proto3,oneof"` // gzipped text or CRDT delta
}

func (*Frame_Telemetry) isFrame_Kind() {}

func (*Frame_Prefetch) isFrame_Kind() {}

func (*Frame_SummaryDelta) isFrame_Kind() {}

var File_proto_events_proto protoreflect.FileDescriptor

var file_proto_events_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x77, 0x69, 0x72, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x09, 0x54,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x54, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x5f,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x69, 0x6e, 0x74, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x41, 0x0a, 0x0c,
	0x50, 0x72, 0x65, 0x66, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x64, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x71, 0x64, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x22,
	0x99, 0x01, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x09, 0x74, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x77,
	0x69, 0x72, 0x65, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x48, 0x00, 0x52,
	0x09, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x30, 0x0a, 0x08, 0x70, 0x72,
	0x65, 0x66, 0x65, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77,
	0x69, 0x72, 0x65, 0x2e, 0x50, 0x72, 0x65, 0x66, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x6e,
	0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x65, 0x66, 0x65, 0x74, 0x63, 0x68, 0x12, 0x25, 0x0a, 0x0d,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x44, 0x65,
	0x6c, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x42, 0x25, 0x5a, 0x23, 0x6c,
	0x65, 0x67, 0x61, 0x6c, 0x2d, 0x61, 0x69, 0x2d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x69, 0x72, 0x65, 0x3b, 0x77, 0x69,
	0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_events_proto_rawDescOnce sync.Once
	file_proto_events_proto_rawDescData = file_proto_events_proto_rawDesc
)

func file_proto_events_proto_rawDescGZIP() []byte {
	file_proto_events_proto_rawDescOnce.Do(func() {
		file_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_events_proto_rawDescData)
	})
	return file_proto_events_proto_rawDescData
}

var file_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_events_proto_goTypes = []interface{}{
	(*Telemetry)(nil),    // 0: wire.Telemetry
	(*PrefetchPlan)(nil), // 1: wire.PrefetchPlan
	(*Frame)(nil),        // 2: wire.Frame
}
var file_proto_events_proto_depIdxs = []int32{
	0, // 0: wire.Frame.telemetry:type_name -> wire.Telemetry
	1, // 1: wire.Frame.prefetch:type_name -> wire.PrefetchPlan
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_events_proto_init() }
func file_proto_events_proto_init() {
	if File_proto_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Telemetry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrefetchPlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_events_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Frame_Telemetry)(nil),
		(*Frame_Prefetch)(nil),
		(*Frame_SummaryDelta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_proto_goTypes,
		DependencyIndexes: file_proto_events_proto_depIdxs,
		MessageInfos:      file_proto_events_proto_msgTypes,
	}.Build()
	File_proto_events_proto = out.File
	file_proto_events_proto_rawDesc = nil
	file_proto_events_proto_goTypes = nil
	file_proto_events_proto_depIdxs = nil
}
