// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: proto/ingest.proto

package ingest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Ingestion_StreamChunks_FullMethodName = "/ingest.Ingestion/StreamChunks"
)

// IngestionClient is the client API for Ingestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestionClient interface {
	StreamChunks(ctx context.Context, opts ...grpc.CallOption) (Ingestion_StreamChunksClient, error)
}

type ingestionClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionClient(cc grpc.ClientConnInterface) IngestionClient {
	return &ingestionClient{cc}
}

func (c *ingestionClient) StreamChunks(ctx context.Context, opts ...grpc.CallOption) (Ingestion_StreamChunksClient, error) {
	stream, err := c.cc.NewStream(ctx, &Ingestion_ServiceDesc.Streams[0], Ingestion_StreamChunks_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &ingestionStreamChunksClient{stream}
	return x, nil
}

type Ingestion_StreamChunksClient interface {
	Send(*IngestChunk) error
	CloseAndRecv() (*IngestAck, error)
	grpc.ClientStream
}

type ingestionStreamChunksClient struct {
	grpc.ClientStream
}

func (x *ingestionStreamChunksClient) Send(m *IngestChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ingestionStreamChunksClient) CloseAndRecv() (*IngestAck, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(IngestAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IngestionServer is the server API for Ingestion service.
// All implementations must embed UnimplementedIngestionServer
// for forward compatibility
type IngestionServer interface {
	StreamChunks(Ingestion_StreamChunksServer) error
	mustEmbedUnimplementedIngestionServer()
}

// UnimplementedIngestionServer must be embedded to have forward compatible implementations.
type UnimplementedIngestionServer struct {
}

func (UnimplementedIngestionServer) StreamChunks(Ingestion_StreamChunksServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamChunks not implemented")
}
func (UnimplementedIngestionServer) mustEmbedUnimplementedIngestionServer() {}

// UnsafeIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestionServer will
// result in compilation errors.
type UnsafeIngestionServer interface {
	mustEmbedUnimplementedIngestionServer()
}

func RegisterIngestionServer(s grpc.ServiceRegistrar, srv IngestionServer) {
	s.RegisterService(&Ingestion_ServiceDesc, srv)
}

func _Ingestion_StreamChunks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestionServer).StreamChunks(&ingestionStreamChunksServer{stream})
}

type Ingestion_StreamChunksServer interface {
	SendAndClose(*IngestAck) error
	Recv() (*IngestChunk, error)
	grpc.ServerStream
}

type ingestionStreamChunksServer struct {
	grpc.ServerStream
}

func (x *ingestionStreamChunksServer) SendAndClose(m *IngestAck) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ingestionStreamChunksServer) Recv() (*IngestChunk, error) {
	m := new(IngestChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Ingestion_ServiceDesc is the grpc.ServiceDesc for Ingestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ingestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingest.Ingestion",
	HandlerType: (*IngestionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChunks",
			Handler:       _Ingestion_StreamChunks_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ingest.proto",
}
