-- Migration: Add consistency defaults for evidence.tags, reports.summary, vectors.embedding
-- Date: 2025-08-22
-- Purpose: Ensure all tables have proper defaults and NOT NULL constraints for worker consistency

-- Ensure pgvector extension exists
CREATE EXTENSION IF NOT EXISTS vector;

-- Update evidence table to add tags field with default empty array
ALTER TABLE evidence 
  ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]'::jsonb NOT NULL;

-- Create GIN index for tags array for fast searching
CREATE INDEX IF NOT EXISTS evidence_tags_idx ON evidence USING gin(tags);

-- Create reports table for detective/legal reports
CREATE TABLE IF NOT EXISTS reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id TEXT NOT NULL,
  evidence_id TEXT, -- Optional - report can be linked to specific evidence
  title TEXT NOT NULL DEFAULT 'Untitled Report',
  doc JSONB DEFAULT '{}'::jsonb NOT NULL, -- Rich text editor content
  summary TEXT DEFAULT '' NOT NULL, -- Always present for auto-summarization worker
  created_by TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL
);

-- Create indexes for reports table
CREATE INDEX IF NOT EXISTS reports_case_id_idx ON reports(case_id);
CREATE INDEX IF NOT EXISTS reports_evidence_id_idx ON reports(evidence_id);
CREATE INDEX IF NOT EXISTS reports_created_by_idx ON reports(created_by);
CREATE INDEX IF NOT EXISTS reports_created_at_idx ON reports(created_at);

-- Update evidence_vectors table to ensure vector is NOT NULL and metadata has default
ALTER TABLE evidence_vectors 
  ALTER COLUMN metadata SET DEFAULT '{}'::jsonb,
  ALTER COLUMN metadata SET NOT NULL;

-- Ensure evidence_vectors.vector is NOT NULL (only after data cleanup if needed)
-- NOTE: This might fail if existing vectors are NULL - handle in application code first
-- ALTER TABLE evidence_vectors ALTER COLUMN vector SET NOT NULL;

-- Update existing evidence records to have empty tags array if NULL
UPDATE evidence SET tags = '[]'::jsonb WHERE tags IS NULL;

-- Update existing reports to have empty summary if NULL (if reports table existed)
-- UPDATE reports SET summary = '' WHERE summary IS NULL;

-- Add foreign key constraints for referential integrity
ALTER TABLE reports 
  ADD CONSTRAINT IF NOT EXISTS fk_reports_case_id 
  FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;

-- Optional: Add foreign key for evidence_id if evidence table uses same ID format
-- ALTER TABLE reports 
--   ADD CONSTRAINT IF NOT EXISTS fk_reports_evidence_id 
--   FOREIGN KEY (evidence_id) REFERENCES evidence(id) ON DELETE SET NULL;

-- Create trigger to update reports.updated_at on changes
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER IF NOT EXISTS update_reports_updated_at 
  BEFORE UPDATE ON reports 
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

-- Ensure all tables are ready for Redis Stream workers
COMMENT ON TABLE evidence IS 'Evidence files with auto-generated tags from workers';
COMMENT ON COLUMN evidence.tags IS 'Auto-generated tags from autotag-worker.ts via Redis streams';
COMMENT ON TABLE reports IS 'Detective/legal reports with auto-generated summaries';
COMMENT ON COLUMN reports.summary IS 'Auto-generated summary from worker processes';
COMMENT ON TABLE evidence_vectors IS 'pgvector embeddings generated by Go ingest-service';