// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.4
// source: recommendations.proto

package recommendations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FOAFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`          // UUID from existing Postgres schema
	MaxDepth      uint32                 `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`         // typically 2 for friend-of-a-friend
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                               // max recommendations to return
	CaseContext   string                 `protobuf:"bytes,4,opt,name=case_context,json=caseContext,proto3" json:"case_context,omitempty"` // optional case ID for context-aware suggestions
	ExcludeIds    []string               `protobuf:"bytes,5,rep,name=exclude_ids,json=excludeIds,proto3" json:"exclude_ids,omitempty"`    // exclude already connected people
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FOAFRequest) Reset() {
	*x = FOAFRequest{}
	mi := &file_recommendations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FOAFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FOAFRequest) ProtoMessage() {}

func (x *FOAFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FOAFRequest.ProtoReflect.Descriptor instead.
func (*FOAFRequest) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{0}
}

func (x *FOAFRequest) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *FOAFRequest) GetMaxDepth() uint32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *FOAFRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FOAFRequest) GetCaseContext() string {
	if x != nil {
		return x.CaseContext
	}
	return ""
}

func (x *FOAFRequest) GetExcludeIds() []string {
	if x != nil {
		return x.ExcludeIds
	}
	return nil
}

type Person struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID matching Postgres users table
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Handle           string                 `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Role             string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`                                                 // attorney, paralegal, investigator
	Specialization   string                 `protobuf:"bytes,5,opt,name=specialization,proto3" json:"specialization,omitempty"`                             // legal specialty
	Confidence       float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`                                   // recommendation confidence score
	RelationshipPath string                 `protobuf:"bytes,7,opt,name=relationship_path,json=relationshipPath,proto3" json:"relationship_path,omitempty"` // e.g., "Alice -> Bob -> Carol"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_recommendations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{1}
}

func (x *Person) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Person) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Person) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *Person) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Person) GetRelationshipPath() string {
	if x != nil {
		return x.RelationshipPath
	}
	return ""
}

type FOAFResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	People           []*Person              `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	Summary          string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"` // LangChain-generated explanation
	TotalFound       uint32                 `protobuf:"varint,3,opt,name=total_found,json=totalFound,proto3" json:"total_found,omitempty"`
	ProcessingTimeMs float64                `protobuf:"fixed64,4,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FOAFResponse) Reset() {
	*x = FOAFResponse{}
	mi := &file_recommendations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FOAFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FOAFResponse) ProtoMessage() {}

func (x *FOAFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FOAFResponse.ProtoReflect.Descriptor instead.
func (*FOAFResponse) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{2}
}

func (x *FOAFResponse) GetPeople() []*Person {
	if x != nil {
		return x.People
	}
	return nil
}

func (x *FOAFResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *FOAFResponse) GetTotalFound() uint32 {
	if x != nil {
		return x.TotalFound
	}
	return 0
}

func (x *FOAFResponse) GetProcessingTimeMs() float64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

type SuggestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                      // raw user input
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                     // default 5-10
	ContextType   string                 `protobuf:"bytes,3,opt,name=context_type,json=contextType,proto3" json:"context_type,omitempty"`       // CASE | DOCUMENT | PERSON | EVIDENCE
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                      // for personalized suggestions
	RecentQueries []string               `protobuf:"bytes,5,rep,name=recent_queries,json=recentQueries,proto3" json:"recent_queries,omitempty"` // query history for better suggestions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestRequest) Reset() {
	*x = SuggestRequest{}
	mi := &file_recommendations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestRequest) ProtoMessage() {}

func (x *SuggestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestRequest.ProtoReflect.Descriptor instead.
func (*SuggestRequest) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{3}
}

func (x *SuggestRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SuggestRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SuggestRequest) GetContextType() string {
	if x != nil {
		return x.ContextType
	}
	return ""
}

func (x *SuggestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SuggestRequest) GetRecentQueries() []string {
	if x != nil {
		return x.RecentQueries
	}
	return nil
}

type Suggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`                       // display text
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // ID to navigate to
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                         // PERSON | DOCUMENT | CASE | EVIDENCE | TAG
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`                     // 0..1 relevance score
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`           // brief explanation why suggested
	Icon          string                 `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`                         // UI icon hint
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`                         // associated tags for filtering
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suggestion) Reset() {
	*x = Suggestion{}
	mi := &file_recommendations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestion) ProtoMessage() {}

func (x *Suggestion) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestion.ProtoReflect.Descriptor instead.
func (*Suggestion) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{4}
}

func (x *Suggestion) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Suggestion) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Suggestion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Suggestion) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Suggestion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Suggestion) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Suggestion) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SuggestResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Suggestions      []*Suggestion          `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	CorrectedQuery   string                 `protobuf:"bytes,2,opt,name=corrected_query,json=correctedQuery,proto3" json:"corrected_query,omitempty"` // spell-corrected input
	Explanation      string                 `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`                             // why these suggestions were chosen
	ProcessingTimeMs float64                `protobuf:"fixed64,4,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SuggestResponse) Reset() {
	*x = SuggestResponse{}
	mi := &file_recommendations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestResponse) ProtoMessage() {}

func (x *SuggestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestResponse.ProtoReflect.Descriptor instead.
func (*SuggestResponse) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{5}
}

func (x *SuggestResponse) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *SuggestResponse) GetCorrectedQuery() string {
	if x != nil {
		return x.CorrectedQuery
	}
	return ""
}

func (x *SuggestResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *SuggestResponse) GetProcessingTimeMs() float64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

type SummarizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                             // document text to summarize
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`                       // legal context (contract, case, evidence)
	Style         string                 `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`                           // brief, detailed, technical
	MaxTokens     uint32                 `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"` // summary length limit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeRequest) Reset() {
	*x = SummarizeRequest{}
	mi := &file_recommendations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeRequest) ProtoMessage() {}

func (x *SummarizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeRequest.ProtoReflect.Descriptor instead.
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{6}
}

func (x *SummarizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SummarizeRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *SummarizeRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *SummarizeRequest) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type SummarizeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Summary          string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`                      // generated summary
	KeyPoints        []string               `protobuf:"bytes,2,rep,name=key_points,json=keyPoints,proto3" json:"key_points,omitempty"` // bullet points
	Confidence       float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`              // summarization confidence
	Model            string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`                          // model used (legal-bert, gemma3-legal)
	ProcessingTimeMs float64                `protobuf:"fixed64,5,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SummarizeResponse) Reset() {
	*x = SummarizeResponse{}
	mi := &file_recommendations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeResponse) ProtoMessage() {}

func (x *SummarizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeResponse.ProtoReflect.Descriptor instead.
func (*SummarizeResponse) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{7}
}

func (x *SummarizeResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SummarizeResponse) GetKeyPoints() []string {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *SummarizeResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SummarizeResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SummarizeResponse) GetProcessingTimeMs() float64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_recommendations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // healthy, degraded, unhealthy
	Services      []*ServiceStatus       `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	UptimeSeconds float64                `protobuf:"fixed64,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_recommendations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetServices() []*ServiceStatus {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *HealthResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ServiceStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // memgraph, redis, postgres
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // up, down, connecting
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ResponseTimeMs float64                `protobuf:"fixed64,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_recommendations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceStatus) GetResponseTimeMs() float64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

var File_recommendations_proto protoreflect.FileDescriptor

const file_recommendations_proto_rawDesc = "" +
	"\n" +
	"\x15recommendations.proto\x12\trecsys.v1\"\xa1\x01\n" +
	"\vFOAFRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\rR\bmaxDepth\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12!\n" +
	"\fcase_context\x18\x04 \x01(\tR\vcaseContext\x12\x1f\n" +
	"\vexclude_ids\x18\x05 \x03(\tR\n" +
	"excludeIds\"\xcd\x01\n" +
	"\x06Person\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06handle\x18\x03 \x01(\tR\x06handle\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12&\n" +
	"\x0especialization\x18\x05 \x01(\tR\x0especialization\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12+\n" +
	"\x11relationship_path\x18\a \x01(\tR\x10relationshipPath\"\xa2\x01\n" +
	"\fFOAFResponse\x12)\n" +
	"\x06people\x18\x01 \x03(\v2\x11.recsys.v1.PersonR\x06people\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x1f\n" +
	"\vtotal_found\x18\x03 \x01(\rR\n" +
	"totalFound\x12,\n" +
	"\x12processing_time_ms\x18\x04 \x01(\x01R\x10processingTimeMs\"\x9f\x01\n" +
	"\x0eSuggestRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12!\n" +
	"\fcontext_type\x18\x03 \x01(\tR\vcontextType\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12%\n" +
	"\x0erecent_queries\x18\x05 \x03(\tR\rrecentQueries\"\xb3\x01\n" +
	"\n" +
	"Suggestion\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"\xc3\x01\n" +
	"\x0fSuggestResponse\x127\n" +
	"\vsuggestions\x18\x01 \x03(\v2\x15.recsys.v1.SuggestionR\vsuggestions\x12'\n" +
	"\x0fcorrected_query\x18\x02 \x01(\tR\x0ecorrectedQuery\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation\x12,\n" +
	"\x12processing_time_ms\x18\x04 \x01(\x01R\x10processingTimeMs\"u\n" +
	"\x10SummarizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x14\n" +
	"\x05style\x18\x03 \x01(\tR\x05style\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\rR\tmaxTokens\"\xb0\x01\n" +
	"\x11SummarizeResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"key_points\x18\x02 \x03(\tR\tkeyPoints\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12,\n" +
	"\x12processing_time_ms\x18\x05 \x01(\x01R\x10processingTimeMs\"\x0f\n" +
	"\rHealthRequest\"\x85\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x124\n" +
	"\bservices\x18\x02 \x03(\v2\x18.recsys.v1.ServiceStatusR\bservices\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x01R\ruptimeSeconds\"\x7f\n" +
	"\rServiceStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x01R\x0eresponseTimeMs2\x95\x02\n" +
	"\tRecommend\x129\n" +
	"\x04FOAF\x12\x16.recsys.v1.FOAFRequest\x1a\x17.recsys.v1.FOAFResponse\"\x00\x12B\n" +
	"\aSuggest\x12\x19.recsys.v1.SuggestRequest\x1a\x1a.recsys.v1.SuggestResponse\"\x00\x12H\n" +
	"\tSummarize\x12\x1b.recsys.v1.SummarizeRequest\x1a\x1c.recsys.v1.SummarizeResponse\"\x00\x12?\n" +
	"\x06Health\x12\x18.recsys.v1.HealthRequest\x1a\x19.recsys.v1.HealthResponse\"\x00BSZQgithub.com/semaj90/dweb-app/go-microservice/proto/recommendations;recommendationsb\x06proto3"

var (
	file_recommendations_proto_rawDescOnce sync.Once
	file_recommendations_proto_rawDescData []byte
)

func file_recommendations_proto_rawDescGZIP() []byte {
	file_recommendations_proto_rawDescOnce.Do(func() {
		file_recommendations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommendations_proto_rawDesc), len(file_recommendations_proto_rawDesc)))
	})
	return file_recommendations_proto_rawDescData
}

var file_recommendations_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_recommendations_proto_goTypes = []any{
	(*FOAFRequest)(nil),       // 0: recsys.v1.FOAFRequest
	(*Person)(nil),            // 1: recsys.v1.Person
	(*FOAFResponse)(nil),      // 2: recsys.v1.FOAFResponse
	(*SuggestRequest)(nil),    // 3: recsys.v1.SuggestRequest
	(*Suggestion)(nil),        // 4: recsys.v1.Suggestion
	(*SuggestResponse)(nil),   // 5: recsys.v1.SuggestResponse
	(*SummarizeRequest)(nil),  // 6: recsys.v1.SummarizeRequest
	(*SummarizeResponse)(nil), // 7: recsys.v1.SummarizeResponse
	(*HealthRequest)(nil),     // 8: recsys.v1.HealthRequest
	(*HealthResponse)(nil),    // 9: recsys.v1.HealthResponse
	(*ServiceStatus)(nil),     // 10: recsys.v1.ServiceStatus
}
var file_recommendations_proto_depIdxs = []int32{
	1,  // 0: recsys.v1.FOAFResponse.people:type_name -> recsys.v1.Person
	4,  // 1: recsys.v1.SuggestResponse.suggestions:type_name -> recsys.v1.Suggestion
	10, // 2: recsys.v1.HealthResponse.services:type_name -> recsys.v1.ServiceStatus
	0,  // 3: recsys.v1.Recommend.FOAF:input_type -> recsys.v1.FOAFRequest
	3,  // 4: recsys.v1.Recommend.Suggest:input_type -> recsys.v1.SuggestRequest
	6,  // 5: recsys.v1.Recommend.Summarize:input_type -> recsys.v1.SummarizeRequest
	8,  // 6: recsys.v1.Recommend.Health:input_type -> recsys.v1.HealthRequest
	2,  // 7: recsys.v1.Recommend.FOAF:output_type -> recsys.v1.FOAFResponse
	5,  // 8: recsys.v1.Recommend.Suggest:output_type -> recsys.v1.SuggestResponse
	7,  // 9: recsys.v1.Recommend.Summarize:output_type -> recsys.v1.SummarizeResponse
	9,  // 10: recsys.v1.Recommend.Health:output_type -> recsys.v1.HealthResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_recommendations_proto_init() }
func file_recommendations_proto_init() {
	if File_recommendations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommendations_proto_rawDesc), len(file_recommendations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommendations_proto_goTypes,
		DependencyIndexes: file_recommendations_proto_depIdxs,
		MessageInfos:      file_recommendations_proto_msgTypes,
	}.Build()
	File_recommendations_proto = out.File
	file_recommendations_proto_goTypes = nil
	file_recommendations_proto_depIdxs = nil
}
