// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.4
// source: vector-service.proto

package vectorservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type SimilarityType int32

const (
	SimilarityType_COSINE      SimilarityType = 0
	SimilarityType_DOT_PRODUCT SimilarityType = 1
	SimilarityType_EUCLIDEAN   SimilarityType = 2
	SimilarityType_MANHATTAN   SimilarityType = 3
)

// Enum value maps for SimilarityType.
var (
	SimilarityType_name = map[int32]string{
		0: "COSINE",
		1: "DOT_PRODUCT",
		2: "EUCLIDEAN",
		3: "MANHATTAN",
	}
	SimilarityType_value = map[string]int32{
		"COSINE":      0,
		"DOT_PRODUCT": 1,
		"EUCLIDEAN":   2,
		"MANHATTAN":   3,
	}
)

func (x SimilarityType) Enum() *SimilarityType {
	p := new(SimilarityType)
	*p = x
	return p
}

func (x SimilarityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimilarityType) Descriptor() protoreflect.EnumDescriptor {
	return file_vector_service_proto_enumTypes[0].Descriptor()
}

func (SimilarityType) Type() protoreflect.EnumType {
	return &file_vector_service_proto_enumTypes[0]
}

func (x SimilarityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimilarityType.Descriptor instead.
func (SimilarityType) EnumDescriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{0}
}

type EmbeddingType int32

const (
	EmbeddingType_LEGAL_BERT           EmbeddingType = 0
	EmbeddingType_NOMIC_EMBED          EmbeddingType = 1
	EmbeddingType_SENTENCE_TRANSFORMER EmbeddingType = 2
	EmbeddingType_CUSTOM               EmbeddingType = 3
)

// Enum value maps for EmbeddingType.
var (
	EmbeddingType_name = map[int32]string{
		0: "LEGAL_BERT",
		1: "NOMIC_EMBED",
		2: "SENTENCE_TRANSFORMER",
		3: "CUSTOM",
	}
	EmbeddingType_value = map[string]int32{
		"LEGAL_BERT":           0,
		"NOMIC_EMBED":          1,
		"SENTENCE_TRANSFORMER": 2,
		"CUSTOM":               3,
	}
)

func (x EmbeddingType) Enum() *EmbeddingType {
	p := new(EmbeddingType)
	*p = x
	return p
}

func (x EmbeddingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmbeddingType) Descriptor() protoreflect.EnumDescriptor {
	return file_vector_service_proto_enumTypes[1].Descriptor()
}

func (EmbeddingType) Type() protoreflect.EnumType {
	return &file_vector_service_proto_enumTypes[1]
}

func (x EmbeddingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmbeddingType.Descriptor instead.
func (EmbeddingType) EnumDescriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{1}
}

// Vector processing request
type VectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	OwnerType     string                 `protobuf:"bytes,2,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Quaternion    *Quaternion            `protobuf:"bytes,4,opt,name=quaternion,proto3" json:"quaternion,omitempty"`
	Points        []float32              `protobuf:"fixed32,5,rep,packed,name=points,proto3" json:"points,omitempty"`
	Options       *ProcessingOptions     `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorRequest) Reset() {
	*x = VectorRequest{}
	mi := &file_vector_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorRequest) ProtoMessage() {}

func (x *VectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorRequest.ProtoReflect.Descriptor instead.
func (*VectorRequest) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{0}
}

func (x *VectorRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *VectorRequest) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *VectorRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *VectorRequest) GetQuaternion() *Quaternion {
	if x != nil {
		return x.Quaternion
	}
	return nil
}

func (x *VectorRequest) GetPoints() []float32 {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *VectorRequest) GetOptions() *ProcessingOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type VectorResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	RotatedPoints    []float32              `protobuf:"fixed32,3,rep,packed,name=rotated_points,json=rotatedPoints,proto3" json:"rotated_points,omitempty"`
	GpuMetrics       *GPUMetrics            `protobuf:"bytes,4,opt,name=gpu_metrics,json=gpuMetrics,proto3" json:"gpu_metrics,omitempty"`
	Error            string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,6,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VectorResponse) Reset() {
	*x = VectorResponse{}
	mi := &file_vector_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorResponse) ProtoMessage() {}

func (x *VectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorResponse.ProtoReflect.Descriptor instead.
func (*VectorResponse) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{1}
}

func (x *VectorResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *VectorResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VectorResponse) GetRotatedPoints() []float32 {
	if x != nil {
		return x.RotatedPoints
	}
	return nil
}

func (x *VectorResponse) GetGpuMetrics() *GPUMetrics {
	if x != nil {
		return x.GpuMetrics
	}
	return nil
}

func (x *VectorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *VectorResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

// Similarity processing request
type SimilarityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	VectorA        []float32              `protobuf:"fixed32,2,rep,packed,name=vector_a,json=vectorA,proto3" json:"vector_a,omitempty"`
	VectorB        []float32              `protobuf:"fixed32,3,rep,packed,name=vector_b,json=vectorB,proto3" json:"vector_b,omitempty"`
	SimilarityType SimilarityType         `protobuf:"varint,4,opt,name=similarity_type,json=similarityType,proto3,enum=vectorservice.SimilarityType" json:"similarity_type,omitempty"`
	Options        *ProcessingOptions     `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimilarityRequest) Reset() {
	*x = SimilarityRequest{}
	mi := &file_vector_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityRequest) ProtoMessage() {}

func (x *SimilarityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityRequest.ProtoReflect.Descriptor instead.
func (*SimilarityRequest) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{2}
}

func (x *SimilarityRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SimilarityRequest) GetVectorA() []float32 {
	if x != nil {
		return x.VectorA
	}
	return nil
}

func (x *SimilarityRequest) GetVectorB() []float32 {
	if x != nil {
		return x.VectorB
	}
	return nil
}

func (x *SimilarityRequest) GetSimilarityType() SimilarityType {
	if x != nil {
		return x.SimilarityType
	}
	return SimilarityType_COSINE
}

func (x *SimilarityRequest) GetOptions() *ProcessingOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type SimilarityResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	SimilarityScore  float32                `protobuf:"fixed32,3,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	GpuMetrics       *GPUMetrics            `protobuf:"bytes,4,opt,name=gpu_metrics,json=gpuMetrics,proto3" json:"gpu_metrics,omitempty"`
	Error            string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,6,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SimilarityResponse) Reset() {
	*x = SimilarityResponse{}
	mi := &file_vector_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityResponse) ProtoMessage() {}

func (x *SimilarityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityResponse.ProtoReflect.Descriptor instead.
func (*SimilarityResponse) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{3}
}

func (x *SimilarityResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SimilarityResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SimilarityResponse) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *SimilarityResponse) GetGpuMetrics() *GPUMetrics {
	if x != nil {
		return x.GpuMetrics
	}
	return nil
}

func (x *SimilarityResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SimilarityResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

// Embedding generation request
type EmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ModelName     string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	EmbeddingType EmbeddingType          `protobuf:"varint,4,opt,name=embedding_type,json=embeddingType,proto3,enum=vectorservice.EmbeddingType" json:"embedding_type,omitempty"`
	Options       *ProcessingOptions     `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_vector_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{4}
}

func (x *EmbeddingRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EmbeddingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EmbeddingRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *EmbeddingRequest) GetEmbeddingType() EmbeddingType {
	if x != nil {
		return x.EmbeddingType
	}
	return EmbeddingType_LEGAL_BERT
}

func (x *EmbeddingRequest) GetOptions() *ProcessingOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type EmbeddingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Embedding        []float32              `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Dimensions       int32                  `protobuf:"varint,4,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	GpuMetrics       *GPUMetrics            `protobuf:"bytes,5,opt,name=gpu_metrics,json=gpuMetrics,proto3" json:"gpu_metrics,omitempty"`
	Error            string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,7,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_vector_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{5}
}

func (x *EmbeddingResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EmbeddingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EmbeddingResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbeddingResponse) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *EmbeddingResponse) GetGpuMetrics() *GPUMetrics {
	if x != nil {
		return x.GpuMetrics
	}
	return nil
}

func (x *EmbeddingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EmbeddingResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

// Batch processing
type BatchRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VectorRequests     []*VectorRequest       `protobuf:"bytes,1,rep,name=vector_requests,json=vectorRequests,proto3" json:"vector_requests,omitempty"`
	SimilarityRequests []*SimilarityRequest   `protobuf:"bytes,2,rep,name=similarity_requests,json=similarityRequests,proto3" json:"similarity_requests,omitempty"`
	EmbeddingRequests  []*EmbeddingRequest    `protobuf:"bytes,3,rep,name=embedding_requests,json=embeddingRequests,proto3" json:"embedding_requests,omitempty"`
	BatchOptions       *BatchOptions          `protobuf:"bytes,4,opt,name=batch_options,json=batchOptions,proto3" json:"batch_options,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_vector_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{6}
}

func (x *BatchRequest) GetVectorRequests() []*VectorRequest {
	if x != nil {
		return x.VectorRequests
	}
	return nil
}

func (x *BatchRequest) GetSimilarityRequests() []*SimilarityRequest {
	if x != nil {
		return x.SimilarityRequests
	}
	return nil
}

func (x *BatchRequest) GetEmbeddingRequests() []*EmbeddingRequest {
	if x != nil {
		return x.EmbeddingRequests
	}
	return nil
}

func (x *BatchRequest) GetBatchOptions() *BatchOptions {
	if x != nil {
		return x.BatchOptions
	}
	return nil
}

type BatchResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BatchId           string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	CompletedCount    int32                  `protobuf:"varint,2,opt,name=completed_count,json=completedCount,proto3" json:"completed_count,omitempty"`
	TotalCount        int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	VectorResults     []*VectorResponse      `protobuf:"bytes,5,rep,name=vector_results,json=vectorResults,proto3" json:"vector_results,omitempty"`
	SimilarityResults []*SimilarityResponse  `protobuf:"bytes,6,rep,name=similarity_results,json=similarityResults,proto3" json:"similarity_results,omitempty"`
	EmbeddingResults  []*EmbeddingResponse   `protobuf:"bytes,7,rep,name=embedding_results,json=embeddingResults,proto3" json:"embedding_results,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_vector_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{7}
}

func (x *BatchResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchResponse) GetCompletedCount() int32 {
	if x != nil {
		return x.CompletedCount
	}
	return 0
}

func (x *BatchResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *BatchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BatchResponse) GetVectorResults() []*VectorResponse {
	if x != nil {
		return x.VectorResults
	}
	return nil
}

func (x *BatchResponse) GetSimilarityResults() []*SimilarityResponse {
	if x != nil {
		return x.SimilarityResults
	}
	return nil
}

func (x *BatchResponse) GetEmbeddingResults() []*EmbeddingResponse {
	if x != nil {
		return x.EmbeddingResults
	}
	return nil
}

// Supporting types
type Quaternion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W             float32                `protobuf:"fixed32,1,opt,name=w,proto3" json:"w,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quaternion) Reset() {
	*x = Quaternion{}
	mi := &file_vector_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quaternion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quaternion) ProtoMessage() {}

func (x *Quaternion) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quaternion.ProtoReflect.Descriptor instead.
func (*Quaternion) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{8}
}

func (x *Quaternion) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Quaternion) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Quaternion) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Quaternion) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type ProcessingOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UseCuda        bool                   `protobuf:"varint,1,opt,name=use_cuda,json=useCuda,proto3" json:"use_cuda,omitempty"`
	UseCublas      bool                   `protobuf:"varint,2,opt,name=use_cublas,json=useCublas,proto3" json:"use_cublas,omitempty"`
	BatchSize      int32                  `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	TimeoutSeconds float32                `protobuf:"fixed32,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	EnableCaching  bool                   `protobuf:"varint,5,opt,name=enable_caching,json=enableCaching,proto3" json:"enable_caching,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessingOptions) Reset() {
	*x = ProcessingOptions{}
	mi := &file_vector_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingOptions) ProtoMessage() {}

func (x *ProcessingOptions) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingOptions.ProtoReflect.Descriptor instead.
func (*ProcessingOptions) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessingOptions) GetUseCuda() bool {
	if x != nil {
		return x.UseCuda
	}
	return false
}

func (x *ProcessingOptions) GetUseCublas() bool {
	if x != nil {
		return x.UseCublas
	}
	return false
}

func (x *ProcessingOptions) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ProcessingOptions) GetTimeoutSeconds() float32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ProcessingOptions) GetEnableCaching() bool {
	if x != nil {
		return x.EnableCaching
	}
	return false
}

type BatchOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxConcurrent  int32                  `protobuf:"varint,1,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	PreserveOrder  bool                   `protobuf:"varint,2,opt,name=preserve_order,json=preserveOrder,proto3" json:"preserve_order,omitempty"`
	TimeoutSeconds float32                `protobuf:"fixed32,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchOptions) Reset() {
	*x = BatchOptions{}
	mi := &file_vector_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOptions) ProtoMessage() {}

func (x *BatchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOptions.ProtoReflect.Descriptor instead.
func (*BatchOptions) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{10}
}

func (x *BatchOptions) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *BatchOptions) GetPreserveOrder() bool {
	if x != nil {
		return x.PreserveOrder
	}
	return false
}

func (x *BatchOptions) GetTimeoutSeconds() float32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type GPUMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GpuName           string                 `protobuf:"bytes,1,opt,name=gpu_name,json=gpuName,proto3" json:"gpu_name,omitempty"`
	MemoryMb          int32                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	ProcessingTimeMs  float32                `protobuf:"fixed32,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	GpuUtilization    float32                `protobuf:"fixed32,4,opt,name=gpu_utilization,json=gpuUtilization,proto3" json:"gpu_utilization,omitempty"`
	MemoryUtilization float32                `protobuf:"fixed32,5,opt,name=memory_utilization,json=memoryUtilization,proto3" json:"memory_utilization,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GPUMetrics) Reset() {
	*x = GPUMetrics{}
	mi := &file_vector_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUMetrics) ProtoMessage() {}

func (x *GPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUMetrics.ProtoReflect.Descriptor instead.
func (*GPUMetrics) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{11}
}

func (x *GPUMetrics) GetGpuName() string {
	if x != nil {
		return x.GpuName
	}
	return ""
}

func (x *GPUMetrics) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *GPUMetrics) GetProcessingTimeMs() float32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *GPUMetrics) GetGpuUtilization() float32 {
	if x != nil {
		return x.GpuUtilization
	}
	return 0
}

func (x *GPUMetrics) GetMemoryUtilization() float32 {
	if x != nil {
		return x.MemoryUtilization
	}
	return 0
}

// Health check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_vector_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{12}
}

type HealthCheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	GpuStatus      *GPUMetrics            `protobuf:"bytes,2,opt,name=gpu_status,json=gpuStatus,proto3" json:"gpu_status,omitempty"`
	DatabaseStatus *DatabaseStatus        `protobuf:"bytes,3,opt,name=database_status,json=databaseStatus,proto3" json:"database_status,omitempty"`
	CacheStatus    *CacheStatus           `protobuf:"bytes,4,opt,name=cache_status,json=cacheStatus,proto3" json:"cache_status,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_vector_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetGpuStatus() *GPUMetrics {
	if x != nil {
		return x.GpuStatus
	}
	return nil
}

func (x *HealthCheckResponse) GetDatabaseStatus() *DatabaseStatus {
	if x != nil {
		return x.DatabaseStatus
	}
	return nil
}

func (x *HealthCheckResponse) GetCacheStatus() *CacheStatus {
	if x != nil {
		return x.CacheStatus
	}
	return nil
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type DatabaseStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Connected         bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	AvgQueryTimeMs    float32                `protobuf:"fixed32,3,opt,name=avg_query_time_ms,json=avgQueryTimeMs,proto3" json:"avg_query_time_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DatabaseStatus) Reset() {
	*x = DatabaseStatus{}
	mi := &file_vector_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseStatus) ProtoMessage() {}

func (x *DatabaseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseStatus.ProtoReflect.Descriptor instead.
func (*DatabaseStatus) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{14}
}

func (x *DatabaseStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *DatabaseStatus) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *DatabaseStatus) GetAvgQueryTimeMs() float32 {
	if x != nil {
		return x.AvgQueryTimeMs
	}
	return 0
}

type CacheStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	CacheHits     int64                  `protobuf:"varint,2,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	CacheMisses   int64                  `protobuf:"varint,3,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	HitRatio      float32                `protobuf:"fixed32,4,opt,name=hit_ratio,json=hitRatio,proto3" json:"hit_ratio,omitempty"`
	MemoryUsageMb int64                  `protobuf:"varint,5,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheStatus) Reset() {
	*x = CacheStatus{}
	mi := &file_vector_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStatus) ProtoMessage() {}

func (x *CacheStatus) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStatus.ProtoReflect.Descriptor instead.
func (*CacheStatus) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{15}
}

func (x *CacheStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *CacheStatus) GetCacheHits() int64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *CacheStatus) GetCacheMisses() int64 {
	if x != nil {
		return x.CacheMisses
	}
	return 0
}

func (x *CacheStatus) GetHitRatio() float32 {
	if x != nil {
		return x.HitRatio
	}
	return 0
}

func (x *CacheStatus) GetMemoryUsageMb() int64 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

// Metrics
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_vector_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{16}
}

type MetricsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests       int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	SuccessfulRequests  int64                  `protobuf:"varint,2,opt,name=successful_requests,json=successfulRequests,proto3" json:"successful_requests,omitempty"`
	FailedRequests      int64                  `protobuf:"varint,3,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	AvgProcessingTimeMs float32                `protobuf:"fixed32,4,opt,name=avg_processing_time_ms,json=avgProcessingTimeMs,proto3" json:"avg_processing_time_ms,omitempty"`
	GpuMetrics          *GPUMetrics            `protobuf:"bytes,5,opt,name=gpu_metrics,json=gpuMetrics,proto3" json:"gpu_metrics,omitempty"`
	DatabaseMetrics     *DatabaseStatus        `protobuf:"bytes,6,opt,name=database_metrics,json=databaseMetrics,proto3" json:"database_metrics,omitempty"`
	CacheMetrics        *CacheStatus           `protobuf:"bytes,7,opt,name=cache_metrics,json=cacheMetrics,proto3" json:"cache_metrics,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_vector_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_vector_service_proto_rawDescGZIP(), []int{17}
}

func (x *MetricsResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *MetricsResponse) GetSuccessfulRequests() int64 {
	if x != nil {
		return x.SuccessfulRequests
	}
	return 0
}

func (x *MetricsResponse) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *MetricsResponse) GetAvgProcessingTimeMs() float32 {
	if x != nil {
		return x.AvgProcessingTimeMs
	}
	return 0
}

func (x *MetricsResponse) GetGpuMetrics() *GPUMetrics {
	if x != nil {
		return x.GpuMetrics
	}
	return nil
}

func (x *MetricsResponse) GetDatabaseMetrics() *DatabaseStatus {
	if x != nil {
		return x.DatabaseMetrics
	}
	return nil
}

func (x *MetricsResponse) GetCacheMetrics() *CacheStatus {
	if x != nil {
		return x.CacheMetrics
	}
	return nil
}

var File_vector_service_proto protoreflect.FileDescriptor

const file_vector_service_proto_rawDesc = "" +
	"\n" +
	"\x14vector-service.proto\x12\rvectorservice\"\xef\x01\n" +
	"\rVectorRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x02 \x01(\tR\townerType\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x129\n" +
	"\n" +
	"quaternion\x18\x04 \x01(\v2\x19.vectorservice.QuaternionR\n" +
	"quaternion\x12\x16\n" +
	"\x06points\x18\x05 \x03(\x02R\x06points\x12:\n" +
	"\aoptions\x18\x06 \x01(\v2 .vectorservice.ProcessingOptionsR\aoptions\"\xe6\x01\n" +
	"\x0eVectorResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0erotated_points\x18\x03 \x03(\x02R\rrotatedPoints\x12:\n" +
	"\vgpu_metrics\x18\x04 \x01(\v2\x19.vectorservice.GPUMetricsR\n" +
	"gpuMetrics\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12,\n" +
	"\x12processing_time_ms\x18\x06 \x01(\x03R\x10processingTimeMs\"\xe4\x01\n" +
	"\x11SimilarityRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bvector_a\x18\x02 \x03(\x02R\avectorA\x12\x19\n" +
	"\bvector_b\x18\x03 \x03(\x02R\avectorB\x12F\n" +
	"\x0fsimilarity_type\x18\x04 \x01(\x0e2\x1d.vectorservice.SimilarityTypeR\x0esimilarityType\x12:\n" +
	"\aoptions\x18\x05 \x01(\v2 .vectorservice.ProcessingOptionsR\aoptions\"\xee\x01\n" +
	"\x12SimilarityResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10similarity_score\x18\x03 \x01(\x02R\x0fsimilarityScore\x12:\n" +
	"\vgpu_metrics\x18\x04 \x01(\v2\x19.vectorservice.GPUMetricsR\n" +
	"gpuMetrics\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12,\n" +
	"\x12processing_time_ms\x18\x06 \x01(\x03R\x10processingTimeMs\"\xdd\x01\n" +
	"\x10EmbeddingRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12C\n" +
	"\x0eembedding_type\x18\x04 \x01(\x0e2\x1c.vectorservice.EmbeddingTypeR\rembeddingType\x12:\n" +
	"\aoptions\x18\x05 \x01(\v2 .vectorservice.ProcessingOptionsR\aoptions\"\x80\x02\n" +
	"\x11EmbeddingResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x04 \x01(\x05R\n" +
	"dimensions\x12:\n" +
	"\vgpu_metrics\x18\x05 \x01(\v2\x19.vectorservice.GPUMetricsR\n" +
	"gpuMetrics\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12,\n" +
	"\x12processing_time_ms\x18\a \x01(\x03R\x10processingTimeMs\"\xba\x02\n" +
	"\fBatchRequest\x12E\n" +
	"\x0fvector_requests\x18\x01 \x03(\v2\x1c.vectorservice.VectorRequestR\x0evectorRequests\x12Q\n" +
	"\x13similarity_requests\x18\x02 \x03(\v2 .vectorservice.SimilarityRequestR\x12similarityRequests\x12N\n" +
	"\x12embedding_requests\x18\x03 \x03(\v2\x1f.vectorservice.EmbeddingRequestR\x11embeddingRequests\x12@\n" +
	"\rbatch_options\x18\x04 \x01(\v2\x1b.vectorservice.BatchOptionsR\fbatchOptions\"\xf3\x02\n" +
	"\rBatchResponse\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12'\n" +
	"\x0fcompleted_count\x18\x02 \x01(\x05R\x0ecompletedCount\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12D\n" +
	"\x0evector_results\x18\x05 \x03(\v2\x1d.vectorservice.VectorResponseR\rvectorResults\x12P\n" +
	"\x12similarity_results\x18\x06 \x03(\v2!.vectorservice.SimilarityResponseR\x11similarityResults\x12M\n" +
	"\x11embedding_results\x18\a \x03(\v2 .vectorservice.EmbeddingResponseR\x10embeddingResults\"D\n" +
	"\n" +
	"Quaternion\x12\f\n" +
	"\x01w\x18\x01 \x01(\x02R\x01w\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\"\xbc\x01\n" +
	"\x11ProcessingOptions\x12\x19\n" +
	"\buse_cuda\x18\x01 \x01(\bR\auseCuda\x12\x1d\n" +
	"\n" +
	"use_cublas\x18\x02 \x01(\bR\tuseCublas\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x02R\x0etimeoutSeconds\x12%\n" +
	"\x0eenable_caching\x18\x05 \x01(\bR\renableCaching\"\x85\x01\n" +
	"\fBatchOptions\x12%\n" +
	"\x0emax_concurrent\x18\x01 \x01(\x05R\rmaxConcurrent\x12%\n" +
	"\x0epreserve_order\x18\x02 \x01(\bR\rpreserveOrder\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x02R\x0etimeoutSeconds\"\xca\x01\n" +
	"\n" +
	"GPUMetrics\x12\x19\n" +
	"\bgpu_name\x18\x01 \x01(\tR\agpuName\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x05R\bmemoryMb\x12,\n" +
	"\x12processing_time_ms\x18\x03 \x01(\x02R\x10processingTimeMs\x12'\n" +
	"\x0fgpu_utilization\x18\x04 \x01(\x02R\x0egpuUtilization\x12-\n" +
	"\x12memory_utilization\x18\x05 \x01(\x02R\x11memoryUtilization\"\x14\n" +
	"\x12HealthCheckRequest\"\x95\x02\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x128\n" +
	"\n" +
	"gpu_status\x18\x02 \x01(\v2\x19.vectorservice.GPUMetricsR\tgpuStatus\x12F\n" +
	"\x0fdatabase_status\x18\x03 \x01(\v2\x1d.vectorservice.DatabaseStatusR\x0edatabaseStatus\x12=\n" +
	"\fcache_status\x18\x04 \x01(\v2\x1a.vectorservice.CacheStatusR\vcacheStatus\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\"\x88\x01\n" +
	"\x0eDatabaseStatus\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x05R\x11activeConnections\x12)\n" +
	"\x11avg_query_time_ms\x18\x03 \x01(\x02R\x0eavgQueryTimeMs\"\xb2\x01\n" +
	"\vCacheStatus\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\x02 \x01(\x03R\tcacheHits\x12!\n" +
	"\fcache_misses\x18\x03 \x01(\x03R\vcacheMisses\x12\x1b\n" +
	"\thit_ratio\x18\x04 \x01(\x02R\bhitRatio\x12&\n" +
	"\x0fmemory_usage_mb\x18\x05 \x01(\x03R\rmemoryUsageMb\"\x10\n" +
	"\x0eMetricsRequest\"\x8e\x03\n" +
	"\x0fMetricsResponse\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12/\n" +
	"\x13successful_requests\x18\x02 \x01(\x03R\x12successfulRequests\x12'\n" +
	"\x0ffailed_requests\x18\x03 \x01(\x03R\x0efailedRequests\x123\n" +
	"\x16avg_processing_time_ms\x18\x04 \x01(\x02R\x13avgProcessingTimeMs\x12:\n" +
	"\vgpu_metrics\x18\x05 \x01(\v2\x19.vectorservice.GPUMetricsR\n" +
	"gpuMetrics\x12H\n" +
	"\x10database_metrics\x18\x06 \x01(\v2\x1d.vectorservice.DatabaseStatusR\x0fdatabaseMetrics\x12?\n" +
	"\rcache_metrics\x18\a \x01(\v2\x1a.vectorservice.CacheStatusR\fcacheMetrics*K\n" +
	"\x0eSimilarityType\x12\n" +
	"\n" +
	"\x06COSINE\x10\x00\x12\x0f\n" +
	"\vDOT_PRODUCT\x10\x01\x12\r\n" +
	"\tEUCLIDEAN\x10\x02\x12\r\n" +
	"\tMANHATTAN\x10\x03*V\n" +
	"\rEmbeddingType\x12\x0e\n" +
	"\n" +
	"LEGAL_BERT\x10\x00\x12\x0f\n" +
	"\vNOMIC_EMBED\x10\x01\x12\x18\n" +
	"\x14SENTENCE_TRANSFORMER\x10\x02\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x032\x80\x04\n" +
	"\rVectorService\x12N\n" +
	"\x0fProcessRotation\x12\x1c.vectorservice.VectorRequest\x1a\x1d.vectorservice.VectorResponse\x12X\n" +
	"\x11ProcessSimilarity\x12 .vectorservice.SimilarityRequest\x1a!.vectorservice.SimilarityResponse\x12U\n" +
	"\x10ProcessEmbedding\x12\x1f.vectorservice.EmbeddingRequest\x1a .vectorservice.EmbeddingResponse\x12K\n" +
	"\fProcessBatch\x12\x1b.vectorservice.BatchRequest\x1a\x1c.vectorservice.BatchResponse0\x01\x12T\n" +
	"\vHealthCheck\x12!.vectorservice.HealthCheckRequest\x1a\".vectorservice.HealthCheckResponse\x12K\n" +
	"\n" +
	"GetMetrics\x12\x1d.vectorservice.MetricsRequest\x1a\x1e.vectorservice.MetricsResponseBOZMgithub.com/semaj90/dweb-app/go-microservice/proto/vectorservice;vectorserviceb\x06proto3"

var (
	file_vector_service_proto_rawDescOnce sync.Once
	file_vector_service_proto_rawDescData []byte
)

func file_vector_service_proto_rawDescGZIP() []byte {
	file_vector_service_proto_rawDescOnce.Do(func() {
		file_vector_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vector_service_proto_rawDesc), len(file_vector_service_proto_rawDesc)))
	})
	return file_vector_service_proto_rawDescData
}

var file_vector_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vector_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_vector_service_proto_goTypes = []any{
	(SimilarityType)(0),         // 0: vectorservice.SimilarityType
	(EmbeddingType)(0),          // 1: vectorservice.EmbeddingType
	(*VectorRequest)(nil),       // 2: vectorservice.VectorRequest
	(*VectorResponse)(nil),      // 3: vectorservice.VectorResponse
	(*SimilarityRequest)(nil),   // 4: vectorservice.SimilarityRequest
	(*SimilarityResponse)(nil),  // 5: vectorservice.SimilarityResponse
	(*EmbeddingRequest)(nil),    // 6: vectorservice.EmbeddingRequest
	(*EmbeddingResponse)(nil),   // 7: vectorservice.EmbeddingResponse
	(*BatchRequest)(nil),        // 8: vectorservice.BatchRequest
	(*BatchResponse)(nil),       // 9: vectorservice.BatchResponse
	(*Quaternion)(nil),          // 10: vectorservice.Quaternion
	(*ProcessingOptions)(nil),   // 11: vectorservice.ProcessingOptions
	(*BatchOptions)(nil),        // 12: vectorservice.BatchOptions
	(*GPUMetrics)(nil),          // 13: vectorservice.GPUMetrics
	(*HealthCheckRequest)(nil),  // 14: vectorservice.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 15: vectorservice.HealthCheckResponse
	(*DatabaseStatus)(nil),      // 16: vectorservice.DatabaseStatus
	(*CacheStatus)(nil),         // 17: vectorservice.CacheStatus
	(*MetricsRequest)(nil),      // 18: vectorservice.MetricsRequest
	(*MetricsResponse)(nil),     // 19: vectorservice.MetricsResponse
}
var file_vector_service_proto_depIdxs = []int32{
	10, // 0: vectorservice.VectorRequest.quaternion:type_name -> vectorservice.Quaternion
	11, // 1: vectorservice.VectorRequest.options:type_name -> vectorservice.ProcessingOptions
	13, // 2: vectorservice.VectorResponse.gpu_metrics:type_name -> vectorservice.GPUMetrics
	0,  // 3: vectorservice.SimilarityRequest.similarity_type:type_name -> vectorservice.SimilarityType
	11, // 4: vectorservice.SimilarityRequest.options:type_name -> vectorservice.ProcessingOptions
	13, // 5: vectorservice.SimilarityResponse.gpu_metrics:type_name -> vectorservice.GPUMetrics
	1,  // 6: vectorservice.EmbeddingRequest.embedding_type:type_name -> vectorservice.EmbeddingType
	11, // 7: vectorservice.EmbeddingRequest.options:type_name -> vectorservice.ProcessingOptions
	13, // 8: vectorservice.EmbeddingResponse.gpu_metrics:type_name -> vectorservice.GPUMetrics
	2,  // 9: vectorservice.BatchRequest.vector_requests:type_name -> vectorservice.VectorRequest
	4,  // 10: vectorservice.BatchRequest.similarity_requests:type_name -> vectorservice.SimilarityRequest
	6,  // 11: vectorservice.BatchRequest.embedding_requests:type_name -> vectorservice.EmbeddingRequest
	12, // 12: vectorservice.BatchRequest.batch_options:type_name -> vectorservice.BatchOptions
	3,  // 13: vectorservice.BatchResponse.vector_results:type_name -> vectorservice.VectorResponse
	5,  // 14: vectorservice.BatchResponse.similarity_results:type_name -> vectorservice.SimilarityResponse
	7,  // 15: vectorservice.BatchResponse.embedding_results:type_name -> vectorservice.EmbeddingResponse
	13, // 16: vectorservice.HealthCheckResponse.gpu_status:type_name -> vectorservice.GPUMetrics
	16, // 17: vectorservice.HealthCheckResponse.database_status:type_name -> vectorservice.DatabaseStatus
	17, // 18: vectorservice.HealthCheckResponse.cache_status:type_name -> vectorservice.CacheStatus
	13, // 19: vectorservice.MetricsResponse.gpu_metrics:type_name -> vectorservice.GPUMetrics
	16, // 20: vectorservice.MetricsResponse.database_metrics:type_name -> vectorservice.DatabaseStatus
	17, // 21: vectorservice.MetricsResponse.cache_metrics:type_name -> vectorservice.CacheStatus
	2,  // 22: vectorservice.VectorService.ProcessRotation:input_type -> vectorservice.VectorRequest
	4,  // 23: vectorservice.VectorService.ProcessSimilarity:input_type -> vectorservice.SimilarityRequest
	6,  // 24: vectorservice.VectorService.ProcessEmbedding:input_type -> vectorservice.EmbeddingRequest
	8,  // 25: vectorservice.VectorService.ProcessBatch:input_type -> vectorservice.BatchRequest
	14, // 26: vectorservice.VectorService.HealthCheck:input_type -> vectorservice.HealthCheckRequest
	18, // 27: vectorservice.VectorService.GetMetrics:input_type -> vectorservice.MetricsRequest
	3,  // 28: vectorservice.VectorService.ProcessRotation:output_type -> vectorservice.VectorResponse
	5,  // 29: vectorservice.VectorService.ProcessSimilarity:output_type -> vectorservice.SimilarityResponse
	7,  // 30: vectorservice.VectorService.ProcessEmbedding:output_type -> vectorservice.EmbeddingResponse
	9,  // 31: vectorservice.VectorService.ProcessBatch:output_type -> vectorservice.BatchResponse
	15, // 32: vectorservice.VectorService.HealthCheck:output_type -> vectorservice.HealthCheckResponse
	19, // 33: vectorservice.VectorService.GetMetrics:output_type -> vectorservice.MetricsResponse
	28, // [28:34] is the sub-list for method output_type
	22, // [22:28] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_vector_service_proto_init() }
func file_vector_service_proto_init() {
	if File_vector_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vector_service_proto_rawDesc), len(file_vector_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vector_service_proto_goTypes,
		DependencyIndexes: file_vector_service_proto_depIdxs,
		EnumInfos:         file_vector_service_proto_enumTypes,
		MessageInfos:      file_vector_service_proto_msgTypes,
	}.Build()
	File_vector_service_proto = out.File
	file_vector_service_proto_goTypes = nil
	file_vector_service_proto_depIdxs = nil
}
