name: Go Build (default, non-legacy)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Build (default, exclude legacy)
        working-directory: go-microservice
        run: |
          go env
          go mod tidy
          go build ./...
