name: Go Legacy Build (weekly)

on:
  schedule:
    - cron: "0 3 * * 1" # Mondays at 03:00 UTC
  workflow_dispatch: {}

jobs:
  build-legacy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Legacy build (allowed to fail)
        working-directory: go-microservice
        run: |
          go env
          go mod tidy
          go build -tags=legacy ./...
